#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

if [[ ! -f .env ]]; then
  echo "Copy .env.example to .env and fill in secrets."
  exit 1
fi

echo "== Python deps (local) =="
cd backend
python3 -m venv .venv 2>/dev/null || true
# shellcheck disable=SC1091
source .venv/bin/activate
pip install -r requirements.txt
playwright install chromium

echo "== Frontend deps =="
cd ../frontend
{
  echo "# Auto-generated by ../setup.sh from prism/.env — gitignored; edit prism/.env as source of truth"
  grep -E '^(NEXT_PUBLIC_|SANITY_API_READ_TOKEN=|SANITY_API_TOKEN=)' "$ROOT/.env" 2>/dev/null || true
  # Local Next.js SSR uses this (Docker Compose overrides via environment: INTERNAL_API_URL=http://backend:8000)
  echo "INTERNAL_API_URL=http://localhost:8000"
} > .env.local
echo "Wrote frontend/.env.local (NEXT_PUBLIC_*, Sanity tokens for server-side GROQ)"
npm ci
npm install @sanity/client

echo "== Sanity studio deps =="
cd ../sanity
npm install

echo "Done. Start stack with: docker compose up --build"
echo "Or dev: backend . && uvicorn main:app --reload ; frontend npm run dev ; sanity npm run dev"
